### PR TITLE
Add rustup command

### PR DESCRIPTION
**Pull request by fazibear**
Now you can:

rustup --list-available-targets
rustup --add-target=asmjs-unknown-emscripten

### CODE REVIEW

**Comment by nickveys** [comment]
I just reverted this, it doesn't seem the work.  The shell script gets downloaded but the rustup shim is not installed in the .asdf/shims directory when installing a new Rust version.  I've never added a shim before, but it looks like (based on this: https://github.com/asdf-vm/asdf/blob/master/lib/commands/reshim.sh) that it will only ever copy that shim if there is an existing executable of the same name.

**Comment by nickveys** [comment]
If you have something I could try to make this work I'd be happy to.

**Comment by fazibear** [comment]
My mistake,
 
It would be great to download `rustup` into each version with hardcoded prefix path.  

I'll try to fix it.

**Comment by fazibear** [comment]
That is correct: https://github.com/code-lever/asdf-rust/pull/10

**Pull request merged**
